# Generated by Django 5.2 on 2025-06-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0002_remove_quizhistory_total_questions2'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='zein_app.question'),
        ),
    ]
