# Generated by Django 5.2 on 2025-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0004_remove_quizhistory_questions_remove_topic_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name_ru']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'name_uz']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='text_uz',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_ru',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_uz',
            field=models.CharField(default='', max_length=100),
        ),
    ]
