# Generated by Django 5.2 on 2025-06-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0005_alter_subject_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.AddField(
            model_name='choice',
            name='text_ru',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_uz',
            field=models.CharField(default='', max_length=255),
        ),
    ]
