# Generated by Django 5.2 on 2025-06-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0006_remove_choice_text_choice_text_ru_choice_text_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text_ru',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text_ru',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text_uz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_uz',
        ),
    ]
