# Generated by Django 5.2 on 2025-05-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0007_alter_results_exam_type_alter_results_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_ar',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ko',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_tr',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ar',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ko',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_tr',
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
