# Generated by Django 5.2 on 2025-05-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0015_remove_contact_type_remove_contact_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitle', models.CharField(max_length=255)),
                ('metaDescription', models.TextField()),
                ('keywords', models.CharField(max_length=512)),
                ('ogImage', models.ImageField(blank=True, null=True, upload_to='seo/og_images/')),
            ],
        ),
    ]
