# Generated by Django 5.2 on 2025-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0016_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('dev', 'Developer')], default='admin', max_length=20),
        ),
    ]
