# Generated by Django 5.2 on 2025-05-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0017_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='courselevel',
            name='features',
        ),
        migrations.RemoveField(
            model_name='courselevel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='name_uz',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='features_ru',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='features_uz',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='title_ru',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='title_uz',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='duration_months',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='level',
            field=models.CharField(default='A1', max_length=10),
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
