# Generated by Django 5.2 on 2025-05-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0018_remove_course_name_remove_courselevel_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
    ]
