# Generated by Django 5.2.1 on 2025-05-27 22:39

import zein_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0019_remove_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='hero_banner',
            field=models.ImageField(null=True, storage=zein_app.storage.CustomS3Storage, upload_to='contact/banner/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=zein_app.storage.CustomS3Storage, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(default='/placeholder.svg', storage=zein_app.storage.CustomS3Storage, upload_to='exam-results/'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='ogImage',
            field=models.ImageField(blank=True, null=True, storage=zein_app.storage.CustomS3Storage, upload_to='seo/og_images/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=zein_app.storage.CustomS3Storage, upload_to='subjects/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(storage=zein_app.storage.CustomS3Storage, upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=zein_app.storage.CustomS3Storage, upload_to='topics/'),
        ),
    ]
