# Generated by Django 5.2.1 on 2025-05-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zein_app', '0020_alter_contact_hero_banner_alter_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
