services:
  # Web service for Django application
  - type: web
    name: quiz-bot-app
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_default_users
    startCommand: gunicorn zeinedtech.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: zeinedtech.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,localhost
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-bot-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false

  # Background worker for Telegram bot
  - type: worker
    name: quiz-bot-worker
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py run_bot
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: zeinedtech.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-bot-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  - name: quiz-bot-db
    plan: starter
