services:
  - type: web
    name: quiz-bot-app
    runtime: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py create_default_users
    startCommand: gunicorn zeinedtech.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: zeinedtech.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,localhost

      # Database from .env
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        value: zein
      - key: DB_USER
        value: zein_user
      - key: DB_PASSWORD
        value: OVjv3hMr45rd9WSegAYxlXSR1UmLLg0e
      - key: DB_HOST
        value: dpg-d0nlpr2li9vc73a211a0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"

      # Optional if your project uses DATABASE_URL
      - key: DATABASE_URL
        value: postgresql://zein_user:OVjv3hMr45rd9WSegAYxlXSR1UmLLg0e@dpg-d0nlpr2li9vc73a211a0-a.oregon-postgres.render.com/zein

      - key: TELEGRAM_BOT_TOKEN
        sync: false

  - type: worker
    name: quiz-bot-worker
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py run_bot
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: zeinedtech.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

      # Database from .env
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        value: zein
      - key: DB_USER
        value: zein_user
      - key: DB_PASSWORD
        value: OVjv3hMr45rd9WSegAYxlXSR1UmLLg0e
      - key: DB_HOST
        value: dpg-d0nlpr2li9vc73a211a0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"

      - key: DATABASE_URL
        value: postgresql://zein_user:OVjv3hMr45rd9WSegAYxlXSR1UmLLg0e@dpg-d0nlpr2li9vc73a211a0-a.oregon-postgres.render.com/zein

      - key: TELEGRAM_BOT_TOKEN
        sync: false
